import Link from "next/link";
import { Brand } from "@/components/brand";
import { SiteHeader } from "@/components/site-header";
import { demo, formatAmount } from "@/lib/demo-state";

function SectionLabel({ number, title, right, inverse = false }: { number: string; title: string; right?: string; inverse?: boolean }) {
  return <div className={`section-label${inverse ? " section-label--inverse" : ""}`}><span>{number} / {title}</span><span className="section-label__rule" /><span>{right ?? "ARTH / COMMUNITY FINANCE"}</span></div>;
}

export default function Home() {
  return <>
    <a className="skip-link" href="#main">Skip to content</a><SiteHeader />
    <main id="main">
      <section className="hero page-shell" aria-labelledby="hero-title">
        <div className="hero__topline eyebrow"><span><i className="eyebrow-dot" /> COMMUNITY FINANCE / BUILT ON STELLAR</span><span>EST. FOR THE COMMUNITY / 001</span></div>
        <div className="hero__grid"><div className="hero__copy"><h1 id="hero-title">COMMUNITY<br />CAPITAL<span className="hero__period">.</span><br /><em>WITHOUT THE<br />MIDDLEMAN.</em></h1><div className="hero__bottom"><p>Pool working capital with your community, access it through sealed bidding, and build verifiable financial history through participation.</p><div><div className="hero__actions"><Link href="/app" className="button button--dark">Launch App <span>↗</span></Link><Link href="#how-it-works" className="text-link">How it works <span>↓</span></Link></div><span className="small-note">01 / A fairer way to move together.</span></div></div></div>
        <div className="hero-art" aria-label="Illustrative Arth community round"><div className="hero-art__number eyebrow">FIG. 01 / A COMMUNITY ROUND <span>ILLUSTRATIVE</span></div><div className="artifact artifact--pot"><div className="artifact__head"><strong>COMMUNITY ROUND</strong><span className="artifact__seal">ROUND 02 / 10</span></div><div className="artifact__meta">CURRENT POT <span>READY TO ALLOCATE</span></div><div className="artifact__value">{formatAmount(demo.pot)}</div><div className="artifact__row"><span>10 MEMBERS</span><strong>₹5,000 / MEMBER</strong></div><div className="artifact__row"><span>ROUND STATUS</span><strong>BIDDING <i className="status-dot" /></strong></div><div className="artifact__seal-row"><span>SEALED BID</span><strong>₹43,000</strong><small>LOCKED</small></div></div><div className="hero-art__rail"><span /><b>COMMIT → REVEAL</b><span>↘</span></div><div className="artifact artifact--result"><div className="artifact__head"><strong>ROUND RESULT</strong><span className="artifact__seal artifact__seal--light">VERIFIED</span></div><div className="artifact__result-label">WINNING PAYOUT</div><div className="artifact__result-value">{formatAmount(demo.winningPayout)} <span>↗</span></div><div className="artifact__outcome"><span className="outcome-mark">✓</span> LOWEST VALID BID</div><div className="artifact__result-foot"><span>COMMUNITY DISCOUNT</span><strong>{formatAmount(demo.discount)}</strong></div></div><div className="hero-art__caption">ILLUSTRATIVE VALUES / NOT LIVE CHAIN STATE</div></div></div>
        <div className="hero__baseline"><span>10 MEMBERS / ONE SHARED CYCLE</span><span>SCROLL TO EXPLORE ↓</span></div>
      </section>
      <div className="trust-strip"><div className="page-shell trust-strip__inner"><span className="eyebrow">BUILT AROUND</span><div className="trust-strip__items"><span>Shared capital</span><span>Sealed bids</span><span>Verifiable history</span></div><span className="trust-strip__end">RULES THE WHOLE COMMUNITY CAN SEE</span></div></div>
      <section className="section-pad page-shell" id="problem"><SectionLabel number="01" title="COMMUNITY CAPITAL" /><h2 className="statement-title">Small businesses need capital.<br /><em>Trust shouldn’t be the bottleneck.</em></h2><div className="statement-aside"><span className="tiny-rule" /><p>Informal finance groups often depend on an organizer for custody, records, and allocation.</p><p>Arth moves the financial rules into a transparent smart-contract system the community can verify.</p></div></section>
      <section className="section-pad section--deep" id="how-it-works"><div className="page-shell"><SectionLabel number="02" title="HOW ARTH WORKS" right="FOUR STEPS / ONE SHARED PROCESS" /><div className="section-intro"><h2>Capital moves<br /><em>with the community.</em></h2><p>A fixed contribution builds each round’s pot. The allocation follows sealed bids and on-chain rules.</p></div><div className="steps-list">{[["01","CONTRIBUTE","Members make the fixed contribution for the current round."],["02","LOCK","Eligible members privately commit their bids."],["03","REVEAL","Bids are revealed only after commitments are locked."],["04","SETTLE","The lowest valid bid receives the payout. The discount is credited to the community."]].map(([number,title,copy])=><div className="step" key={number}><span className="step__number">{number}</span><h3>{title}</h3><p>{copy}</p><span className="step__glyph">↗</span></div>)}</div></div></section>
      <section className="section-pad page-shell" id="sealed-bidding"><SectionLabel number="03" title="SEALED BIDDING" right="PRIVATE FIRST / VERIFIABLE AFTER" /><div className="section-intro section-intro--split"><h2>Reveal the bid.<br /><em>Not before it matters.</em></h2><p>Sealed bidding stops others from seeing your bid. The commitment stops you from changing your own bid.</p></div><div className="bidding-window"><div className="bidding-pane bidding-pane--commit"><div className="bidding-pane__head eyebrow"><span>COMMIT PHASE</span><span>01 / LOCKED</span></div><h3>The amounts stay hidden.</h3>{demo.bids.map(({name})=><div className="bid-row" key={name}><span>{name}</span><strong className="bid-mask" aria-label="Amount hidden">████████</strong><small>LOCKED</small></div>)}<p>Each participant submits a hash. No bid amount is stored in the commitment.</p></div><div className="bidding-aperture"><span>AFTER DEADLINE</span>→</div><div className="bidding-pane bidding-pane--reveal"><div className="bidding-pane__head eyebrow"><span>REVEAL PHASE</span><span>02 / VERIFIED</span></div><h3>Then the bids are seen.</h3>{demo.bids.map(({name,amount})=><div className={`bid-row${name === "Rahul" ? " bid-row--winner" : ""}`} key={name}><span>{name}</span><strong>{formatAmount(amount)}</strong><small>{name === "Rahul" ? "LOWEST" : "VALID"}</small></div>)}<div className="winner-strip"><span>WINNER <b>RAHUL</b></span><strong>₹43,000</strong></div></div></div></section>
      <section className="section-pad discount-section" id="discount"><div className="page-shell"><SectionLabel number="04" title="THE COMMUNITY DISCOUNT" right="THE MATH IS PUBLIC" /><div className="section-intro section-intro--split"><h2>The difference<br /><em>stays with everyone.</em></h2><p>The winner accepts a discounted payout for receiving this round’s capital. The difference becomes claimable community credit under the protocol.</p></div><div className="discount-equation"><div><span className="eyebrow">ROUND POT</span><strong>₹50,000</strong></div><span className="discount-operator">−</span><div><span className="eyebrow">WINNING PAYOUT</span><strong>₹43,000</strong></div><span className="discount-operator">=</span><div className="discount-equation__answer"><span className="eyebrow">COMMUNITY DISCOUNT</span><strong>₹7,000</strong></div></div><div className="discount-caption"><span>10 MEMBERS</span><span>₹700 EARNED PER MEMBER</span><span>INCLUDES THE WINNER / ILLUSTRATIVE ROUND</span></div></div></section>
      <section className="section-pad page-shell" id="participation"><SectionLabel number="05" title="CONTINUED PARTICIPATION" /><div className="participation-grid"><div><h2 className="section-title">Getting the payout<br /><em>doesn’t end the commitment.</em></h2><p className="section-copy">A member who receives the payout continues making the same fixed contribution through the remaining rounds of the cycle.</p></div><div className="participation-ledger"><div className="ledger-head"><strong>RAHUL</strong><span>CYCLE 01 / 10 ROUNDS</span></div><div className="ledger-highlight"><span>PAYOUT RECEIVED</span><strong>ROUND 02 <b>✓</b></strong></div>{[3,4,5].map((round)=><div className="ledger-row" key={round}><span>ROUND {String(round).padStart(2,"0")} CONTRIBUTION</span><strong>₹5,000 <b>✓</b></strong></div>)}<div className="ledger-row ledger-row--faded"><span>ROUND 06 → 10</span><strong>OBLIGATION CONTINUES</strong></div></div></div></section>
      <section className="section-pad history-section" id="history"><div className="page-shell"><SectionLabel number="06" title="VERIFIABLE FINANCIAL HISTORY" right="FACTS FROM PROTOCOL ACTIVITY" /><div className="section-intro section-intro--split"><h2>Participation<br /><em>you can prove.</em></h2><p>Arth records what members actually do: contribute, receive a payout, continue contributing, and finish a cycle.</p></div><div className="history-window"><div className="history-window__top eyebrow"><span>ARTH / PARTICIPATION HISTORY</span><span>EXAMPLE / COMPLETED CYCLE</span></div><div className="history-window__hero"><div><span className="eyebrow">MEMBER RECORD</span><h3>Rahul’s<br />participation.</h3></div><div className="history-window__seal">ON-CHAIN<br />FACTS ↗</div></div><div className="history-window__grid">{[["CONTRIBUTIONS","10 / 10"],["TOTAL CONTRIBUTED","₹50,000"],["PAYOUTS RECEIVED","1"],["PAYOUT AMOUNT","₹43,000"],["POST-PAYOUT CONTRIBUTIONS","8 / 8"],["CYCLES COMPLETED","1"],["DISCOUNTS EARNED*","₹6,700"],["DISCOUNTS CLAIMED","₹0"]].map(([label,value])=><div key={label}><span>{label}</span><strong>{value}</strong></div>)}</div><div className="history-window__foot">*Illustrative cumulative value across a completed cycle. Verifiable participation, not an opaque credit score.</div></div></div></section>
      <section className="section-pad protocol-section" id="protocol"><div className="page-shell"><SectionLabel number="07" title="BUILT ON STELLAR" right="SOROBAN / FREIGHTER" inverse /><div className="protocol-grid"><div><h2 className="section-title">Rules that live<br /><em>in the open.</em></h2><p className="section-copy">Soroban smart contracts enforce the mechanics. Freighter signs member transactions. Financial history comes from actual protocol activity.</p><Link href="/app" className="text-link text-link--light">Explore the app <span>↗</span></Link></div><div className="protocol-list"><div><span>01</span><strong>Cycle membership &amp; contributions</strong></div><div><span>02</span><strong>Sealed commitments &amp; reveal verification</strong></div><div><span>03</span><strong>Winner selection &amp; payout settlement</strong></div><div><span>04</span><strong>Discount accounting &amp; financial history</strong></div><div className="protocol-list__foot">STELLAR / SOROBAN / FREIGHTER</div></div></div></div></section>
      <section className="section-pad final-section"><div className="page-shell"><SectionLabel number="08" title="YOUR COMMUNITY / YOUR CAPITAL" /><h2>Community finance,<br /><em>with rules everyone can verify.</em></h2><div className="final-section__bottom"><p>Pool capital. Bid fairly. Participate consistently. Build history you can prove.</p><Link href="/app" className="button button--dark">Launch Arth <span>↗</span></Link></div></div></section>
    </main>
    <footer className="site-footer"><div className="page-shell site-footer__main"><div><Brand inverse /><p>Community capital, governed by code.</p></div><div className="site-footer__col"><span>EXPLORE</span><Link href="#how-it-works">How it works</Link><Link href="#sealed-bidding">Sealed bidding</Link><Link href="#history">History</Link><Link href="#protocol">Protocol</Link></div><div className="site-footer__col"><span>BUILT ON</span><strong>Stellar / Soroban</strong></div></div><div className="page-shell site-footer__bottom"><span>ARTH © 2026</span><span>COMMUNITY CAPITAL / BUILT ON STELLAR</span><Link href="#main">BACK TO TOP ↑</Link></div></footer>
  </>;
}
