"use client";
import { useState } from "react";
import Link from "next/link";
import { demo, formatAmount } from "@/lib/demo-state";

type Preview = "pending" | "ready";

export default function CyclePage() {
  const [preview, setPreview] = useState<Preview>("pending");
  const state = demo.contributionPreview[preview];
  const ready = preview === "ready";
  return <div className="app-screen"><div className="app-page-heading"><div><span className="app-kicker"><i /> 02 / CURRENT CYCLE</span><h1>Progress is<br /><em>shared.</em></h1><p>Each member’s fixed contribution forms this round’s pot.</p></div><span className="app-page-index">CYCLE 001 / ROUND 01</span></div>

    <div className="cycle-preview-switch"><span>ILLUSTRATIVE VIEWS / NO TRANSACTIONS</span><div role="group" aria-label="Contribution example state"><button type="button" aria-pressed={!ready} onClick={()=>setPreview("pending")}>BEFORE CONTRIBUTION</button><button type="button" aria-pressed={ready} onClick={()=>setPreview("ready")}>POT READY</button></div></div>

    <section className="cycle-contribution" aria-label="Current round contribution"><div className="cycle-contribution__main"><span className="app-panel-kicker">CURRENT ROUND / {String(demo.currentRound).padStart(2,"0")} OF {demo.totalRounds}</span><h2>{ready ? "Your part is in." : "Your contribution is next."}</h2><p>Every cycle member contributes the fixed amount for the current round. Once all required contributions are collected, the round pot is ready for allocation.</p><div className="cycle-contribution__facts"><div><span>YOUR CONTRIBUTION</span><strong>{formatAmount(demo.contribution)}</strong></div><div><span>STATUS</span><strong>{state.myStatus}</strong></div></div><button type="button" className="button button--dark cycle-contribution__button" disabled>CONTRIBUTE {formatAmount(demo.contribution)} <span>↗</span></button><small>Interface preview only. The button cannot sign, submit, or change the example state.</small></div><div className="cycle-contribution__aside"><span className="app-panel-kicker">COMMUNITY / CYCLE 001</span><strong>INCLUDED</strong><p>Your wallet would join the community and be included in a cycle before contributions begin.</p><button type="button" className="preview-outline-button" disabled>JOIN COMMUNITY / CYCLE ↗</button><small>Wallet connection and joining arrive with the deployed contract.</small></div></section>

    <section className="pot-progress" aria-label="Community pot progress"><div className="pot-progress__header"><span className="app-kicker">THE POT / BUILT TOGETHER</span><span>{ready ? "POT READY" : "ONE CONTRIBUTION REMAINING"}</span></div><div className="pot-equation"><div><span>MEMBERS</span><strong>{demo.members}</strong></div><b>×</b><div><span>EACH CONTRIBUTES</span><strong>{formatAmount(demo.contribution)}</strong></div><b>=</b><div><span>ROUND POT</span><strong>{formatAmount(demo.pot)}</strong></div></div><div className="pot-progress__collected"><div><span>{ready ? "POT READY" : "COLLECTED"}</span><strong>{formatAmount(state.collected)} <small>/ {formatAmount(demo.pot)}</small></strong></div><div className="pot-progress__track"><span style={{width:`${state.membersPaid * 10}%`}} /></div><p>{state.membersPaid} / {demo.members} MEMBERS CONTRIBUTED</p></div></section>

    <div className="cycle-columns"><section className="cycle-member-list"><div className="app-section-head"><h2>Member contributions</h2><span>ROUND 01 / FRONTEND METADATA</span></div><div className="cycle-member-list__rows">{demo.contributionPreview.members.map((member,index)=><div key={member}><span>{String(index+1).padStart(2,"0")}</span><strong>{member}</strong><small className={!ready && member==="You" ? "is-pending" : ""}>{!ready && member==="You" ? "PENDING" : "PAID ✓"}</small></div>)}</div></section><section className="cycle-request"><span className="app-kicker">NEXT / AFTER THE POT IS READY</span><h2>Request this round’s<br /><em>payout.</em></h2><p>Eligible members who have not yet received a payout in this cycle can enter the current allocation round.</p><div className="cycle-request__status"><span>ROUND POT</span><strong>{ready ? "READY" : "BUILDING"}</strong></div><button type="button" className="button button--dark" disabled>REQUEST PAYOUT <span>↗</span></button><small>{ready ? "Request action is an interface preview until Step 5B." : "Preview “Pot ready” above to see the eligible request stage."}</small><Link href="/app/bid" className="text-link">See sealed bidding <span>↗</span></Link></section></div>

    <div className="app-section-head cycle-timeline-heading"><h2>Cycle timeline</h2><span>01 — 10 / ONE PAYOUT PER MEMBER</span></div><div className="cycle-timeline">{Array.from({length:demo.totalRounds},(_,index)=>{const round=index+1;return <div className={`cycle-row${round===demo.currentRound?" cycle-row--active":""}`} key={round}><span>{String(round).padStart(2,"0")}</span><strong>ROUND {String(round).padStart(2,"0")}</strong><span>{round===demo.currentRound?ready?"POT READY":"CONTRIBUTING":"UPCOMING —"}</span><b>{round===demo.currentRound?"↗":"—"}</b></div>})}</div>
    <div className="cycle-note"><span className="app-kicker">AFTER A PAYOUT</span><p>Winning a round does not end membership. The member continues the normal fixed contribution through the remaining cycle rounds.</p></div>
  </div>;
}
